# Generated by Django 5.1.7 on 2025-03-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_saved',
            field=models.BooleanField(default='True'),
        ),
    ]
