# Generated by Django 5.1.7 on 2025-03-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_saved',
            field=models.BooleanField(default=True),
        ),
    ]
